routes/backend.php
<?php

use App\Http\Controllers\Backend\ColorController;
use App\Http\Controllers\Backend\SizeController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Backend\AdminController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\PermissionController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\SubCategoryController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\SocalMediaController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\Backend\SiteSettingController;
use App\Http\Controllers\Backend\OfferController;
use App\Http\Controllers\Backend\BarandController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;

Auth::routes();

Route::get('/admin', function () {
    return redirect()->route('admin.login');
});

Route::get('/admin/login', function () {
    return view('backend.login');
})->name('admin.login');

Route::get('/dashboard', function () {
    if (Auth::check()) {
        $user = Auth::user();
        if ($user->hasAnyRole(['admin', 'manager'])) {
            return redirect()->route('admin.dashboard');
        } else {
            return redirect()->route('dashboard');
        }
    }
});

Route::get('/user/dashboard', [HomeController::class, 'dashboard'])->middleware('auth')->name('dashboard');
Route::get('/admin/dashboard', [AdminController::class, 'index'])->middleware('auth')->name('admin.dashboard');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin'], function() {

    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('permissions', PermissionController::class);

    Route::controller(CategoryController::class)
        ->prefix('categories')
        ->as('categories.')
        ->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/create', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/show/{category}', 'show')->name('show');
            Route::get('/edit/{category}', 'edit')->name('edit');
            Route::post('/update/{category}', 'update')->name('update');
            Route::get('/destroy/{category}', 'destroy')->name('destroy');
            Route::get('/status/{category}', 'status')->name('status');
        });

    Route::controller(SubCategoryController::class)
        ->prefix('sub/categories')
        ->as('sub.categories.')
        ->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/create', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/show/{sub_category}', 'show')->name('show');
            Route::get('/edit/{sub_category}', 'edit')->name('edit');
            Route::post('/update/{sub_category}', 'update')->name('update');
            Route::get('/destroy/{sub_category}', 'destroy')->name('destroy');
            Route::get('/status/{sub_category}', 'status')->name('status');
        });
    Route::controller(BarandController::class)
        ->prefix('brands')
        ->as('brands.')
        ->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/create', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/show/{brand}', 'show')->name('show');
            Route::get('/edit/{brand}', 'edit')->name('edit');
            Route::post('/update/{brand}', 'update')->name('update');
            Route::get('/destroy/{brand}', 'destroy')->name('destroy');
            Route::get('/status/{brand}', 'status')->name('status');
        });
    Route::controller(OrderController::class)
        ->prefix('orders')
        ->as('orders.')
        ->group(function () {
            Route::get('/cancle/requests', 'cancle_request')->name('canclerequest');
            Route::get('{status}', 'index')->name('index');
            Route::get('/create', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/show/{order}', 'show')->name('show');
            Route::get('/edit/{category}', 'edit')->name('edit');
            Route::post('/update/{category}', 'update')->name('update');
            Route::get('/destroy/{category}', 'destroy')->name('destroy');
            Route::get('/status/{category}', 'status')->name('status');
            Route::post('/update-status/{order}','updateStatus')->name('updateStatus');
            Route::post('/cancle/statusUpdate/{cancle_order}','cancle_statusUpdate')->name('cancle.statusUpdate');
            Route::post('/payment/statusUpdate/{payment}','payment_statusUpdate')->name('payment.updateStatus');

        });

    Route::controller(ProductController::class)
        ->prefix('products')
        ->as('products.')
        ->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/create', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/show/{product}', 'show')->name('show');
            Route::get('/edit/{product}', 'edit')->name('edit');
            Route::post('/update/{product}', 'update')->name('update');
            Route::get('/destroy/{product}', 'destroy')->name('destroy');
            Route::get('/status/{product}', 'status')->name('status');
            Route::post('/meta/update/{product}', 'meta_update')->name('meta.update');
            Route::post('/image/update/{product}', 'image_update')->name('image.update');
            Route::get('/image/delete/{image}', 'image_delete')->name('image.delete');
            Route::get('/get/subcategories/{category}', 'getSubcategories');
            Route::get('/stock/out', 'stockOut')->name('stock.out');
            Route::get('/get/color_size/{color}/{size}', 'color_size');
            Route::post('/varient/update/{color_size}', 'varient_update')->name('varient.update');
        });

    Route::controller(SizeController::class)
            ->prefix('sizes')
            ->as('sizes.')
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::post('/store', 'store')->name('store');
                Route::post('/update/{size}', 'update')->name('update');
        });
    Route::controller(ColorController::class)
            ->prefix('colors')
            ->as('colors.')
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::post('/store', 'store')->name('store');
                Route::post('/update/{color}', 'update')->name('update');
        });

    Route::controller(SiteSettingController::class)
            ->prefix('pages')
            ->as('pages.')
            ->group(function () {
                Route::get('/home', 'home')->name('home');
                Route::get('/contact', 'contact')->name('contact');
                Route::get('/message_delete', 'delete')->name('message.delete');
                Route::get('/faq', 'faq')->name('faq');
                Route::get('/about', 'about')->name('about');
                Route::get('/privacy', 'privacy')->name('privacy');
                Route::get('/termsAndCondition', 'terms')->name('termsAndCondition');
                Route::get('/shippingAndReturn', 'shipping')->name('shipping');
                Route::post('/update/{service}', 'update')->name('update');
        });

    Route::POST('/delete_message/{delet_item}',[ContactController::class,'delete'])->name('delete.message');
    Route::POST('/update_socialmedia/{id}',[SocalMediaController::class,'update'])->name('socal.media.update');
    Route::get('socalmedia/address',[SocalMediaController::class,'index'])->name('socal.media');
    Route::post('logo/update/{logo_update}',[SocalMediaController::class,'logo_update'])->name('logo.update');

    Route::controller(OfferController::class)
        ->prefix('offers')
        ->as('offer.')
        ->group(function () {
            Route::get('/', 'index')->name('index');
            Route::get('/create', 'create')->name('create');
            Route::post('/store', 'store')->name('store');
            Route::get('/show/{offer}', 'show')->name('show');
            Route::get('/edit/{offer}', 'edit')->name('edit');
            Route::post('/update/{offer}', 'update')->name('update');
            Route::get('/destroy/{offer}', 'destroy')->name('destroy');
            Route::get('/status/{offer}', 'status')->name('status');
            Route::get('/send/sms/{offer}', 'send_sms')->name('send.sms');
            Route::post('/send/mail', 'send_mail')->name('send.mail');
        });
    Route::get('all/transactions',[AdminController::class,'allTransactions'])->name('all.transactions');
    Route::get('customer/lists',[AdminController::class,'customerLists'])->name('customer.lists');
    Route::get('cache-clear',[AdminController::class,'cacheClear'])->name('cache-clear');
});

routes/web.php
<?php
// FrontEnd Controllers

use App\Http\Controllers\CartController;
use App\Http\Controllers\ShopController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\Auth\CustomLoginController;
use App\Http\Controllers\ProfileController;

Route::get('/',[HomeController::class,'index']);
Route::get('/product/details/{slug}', [ShopController::class, 'product_details'])->name('product.details');
Route::get('/get-sizes/{productColor}', [ShopController::class, 'colorSize']);
Route::get('/get-price/{colorSize}', [ShopController::class, 'getPrice']);

Route::get('/about',[HomeController::class, 'about'])->name('about');
Route::get('/contact-us',[HomeController::class, 'contact_us'])->name('contact.us');
Route::get('/faq',[HomeController::class,'faq'])->name('faq');
Route::get('/privacy-policy',[HomeController::class, 'privacy_policy'])->name('privacy.policy');
Route::get('/terms-conditions',[HomeController::class, 'terms_condition'])->name('terms.condition');
Route::get('/shipping-policys',[HomeController::class, 'shipping_policy'])->name('shipping.policy');
Route::get('/product/search', [ShopController::class, 'search'])->name('product.search');

Route::post('/send_message',[ContactController::class,'store'])->name('send.message');

Route::get('/find/product/{product}',[CartController::class,'find_product'])->name('find.product');
Route::get('/cart/count',[CartController::class,'cart_count'])->name('cart.count');
Route::post('/cart/update',[CartController::class,'update'])->name('cart.update');
Route::get('/cart/products',[CartController::class,'cart_products'])->name('cart.products');
Route::get('/cart',[CartController::class, 'cart'])->name('cart');
// web.php or routes file
Route::post('/orders/cancel', [CartController::class,'orderCancel'])->name('orders.cancle.request');
Route::get('/remove-item/{cart}',[CartController::class, 'remove_item'])->name('remove.item');
Route::get('/remove-all',[CartController::class, 'remove_all'])->name('cart.remove.all');
Route::get('/remove/details',[CartController::class, 'order_details'])->name('order.details');

// Checkout
Route::get('/checkout', [CartController::class, 'checkout'])->name('checkout');
Route::post('/cart/checkout', [CartController::class, 'cart_checkout'])->middleware('auth')->name('cart.checkout');
Route::get('/order-success/{order}', [CartController::class, 'invoice'])->name('order-success');

// Custom Login
Route::post('/custom/login', [CustomLoginController::class, 'login'])->name('custom.login');

//Profile
Route::post('/profile',[ProfileController::class,'profile'])->middleware('auth')->name('profile');

Route::post('/profile/create',[ProfileController::class,'create'])->name('profile.create');
Route::post('/profile/update/{profile}',[ProfileController::class,'update'])->name('profile.update');

// For add to cart
Route::post('add/cart/{slug}',[CartController::class,'addToCart'])->name('addTo.cart');

Route::get('/offer/{offer}',[ShopController::class, 'offer'])->name('offer');
Route::get('/offer-product/{product}/{offer}',[ShopController::class, 'offer_product'])->name('offer.product');
Route::post('offer/cart/{slug}',[CartController::class, 'offerCart'])->name('offer.cart');

Route::get('/shop/{category?}/{sub_category?}',[ShopController::class, 'filter'])->name('filter');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function sub_categories()
    {
        return $this->belongsToMany(SubCategory::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Payment;
use App\Models\Product;
use App\Models\Order;
use App\Models\Category;
use App\Models\Brand;
use App\Models\User;
use Artisan;

class AdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $data = [];
        $data['users'] = User::count();
        $data['product'] = Product::count();
        $data['orderCount'] = Order::count();
        $data['catagory'] = Category::count();
        $data['brand'] = Brand::count();
        $data['stock'] = Product::sum('stock');

        $data['available_products'] = Product::with('category', 'sub_category')->where('stock', '>', 2)->orderBy('id', 'DESC')->get();
        $data['stock_out_products'] = Product::with('category', 'sub_category')->where('stock', '<=', 2)->orderBy('id', 'DESC')->get();
        $data['latest_order'] = Order::latest()->get();
        return view('backend.index', compact('data'));
    }
    public function allTransactions()
    {
        $transections = Payment::orderBy('id', 'DESC')->get();
        return view('backend.transection', compact('transections'));
    }
    public function customerLists()
    {
        $users = User::doesntHave('roles')->get();
        return view('backend.user_lists', compact('users'));
    }
    public function cacheClear()
    {
        Artisan::call('cache:clear');
        Artisan::call('route:cache');
        Artisan::call('config:cache');
        Artisan::call('view:clear');

        return redirect()->back()->with('success', 'Offer Update Successfully');
        // return redirect()->back()->with('success', 'Cache Clear Successfully');
    }
}

app/Http/Controllers/Backend/ColorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Color;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class ColorController extends Controller
{
    public function index()
    {
        $colors = Color::orderBy('status')->get();
        return view('backend.color', compact('colors'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'=>'required|string|unique:colors,name',
            'code'=>'required|string'
        ]);

        if ($validator->fails()) {
            return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $input = $validator->validated();

        try {
            $input['slug'] = Str::slug($input['name']);
            Color::create($input);

            return redirect()->back()->with('success', 'Color Created Successfully');
        } catch (\Exception $e) {
            return redirect()->back()->withInput()->withErrors(['error' => $e->getMessage()]);
        }
    }

    public function update(Request $request, Color $color)
    {
        $validator = Validator::make($request->all(), [
            'name'=>'required|string|unique:colors,name,'.$color->id,
            'code'=>'required|string'
        ]);

        if ($validator->fails()) {
            return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $input = $validator->validated();

        try {
            $input['slug'] = Str::slug($input['name']);
            $color->update($input);

            return redirect()->back()->with('success', 'Color Update Successfully');
        } catch (\Exception $e) {
            return redirect()->back()->withInput()->withErrors(['error' => $e->getMessage()]);
        }
    }
}

resources/views/backend/category/create.blade.php
@extends('layouts.backend')

@section('title', 'Create Category')
@section('content')

<div class="col-md-12 col-sm-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Create Category <small><a class="btn btn-warning" href="{{ route('categories.index') }}"> Back</a></small></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <form action="{{route('categories.store')}}" method="POST" enctype="multipart/form-data">
                @csrf

                <span class="section">Category</span>

                @include('backend.includes.message')

                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Name<span class="required text-danger">*</span></label>
                    <div class="col-md-6 col-sm-6">
                        <input class="form-control" name="name" placeholder="Name" required="required" value="{{ old('name') }}"/>
                    </div>
                </div>
                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Title</label>
                    <div class="col-md-6 col-sm-6">
                        <input class="form-control" name="meta_title" placeholder="Meta Title" value="{{ old('meta_title') }}"/>
                    </div>
                </div>
                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Description</label>
                    <div class="col-md-6 col-sm-6">
                        <textarea class="form-control" name="meta_description" cols="30" rows="10">{{ old('meta_description') }}</textarea>
                    </div>
                </div>
                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Image (1200 x 627)</label>
                    <div class="col-md-6 col-sm-6">
                        <input class="form-control" type="file" name="meta_image" id="meta_image" onchange="previewImage(this,'image_preview')" value="{{ old('meta_image') }}"/>
                        <br>
                        <img class="img-fluid" id="image_preview" src="{{ getImageUrl('') }}"
                            alt="Profile Image" accept="image/png, image/jpeg" width="400px" height="209px">
                    </div>
                </div>

                <div class="ln_solid">
                    <div class="form-group">
                        <div class="col-md-6 offset-md-3 mt-3">
                            <button type='submit' class="btn btn-primary">Create</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@push('scripts')
    <script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'meta_description' );
    </script>
@endpush
@endsection

resources/views/backend/category/edit.blade.php
@extends('layouts.backend')

@section('title', 'Edit Category')
@section('content')

<div class="col-md-12 col-sm-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Edit Category <small><a class="btn btn-warning" href="{{ route('categories.index') }}"> Back</a></small></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <form action="{{route('categories.update', $category->id)}}" method="POST" enctype="multipart/form-data">
                @csrf

                <span class="section">Category</span>

                @include('backend.includes.message')

                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Name<span class="required text-danger">*</span></label>
                    <div class="col-md-6 col-sm-6">
                        <input class="form-control" name="name" placeholder="Name" required="required" value="{{ $category->name }}"/>
                    </div>
                </div>
                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Title</label>
                    <div class="col-md-6 col-sm-6">
                        <input class="form-control" name="meta_title" placeholder="Meta Title" value="{{ $category->meta_title }}"/>
                    </div>
                </div>
                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Description</label>
                    <div class="col-md-6 col-sm-6">
                        <textarea class="form-control" name="meta_description" cols="30" rows="10">{{ $category->meta_description }}</textarea>
                    </div>
                </div>
                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Image (1200 x 627)</label>
                    <div class="col-md-6 col-sm-6">
                        <input class="form-control" type="file" name="meta_image" id="meta_image" onchange="previewImage(this,'image_preview')" value="{{ old('meta_image') }}"/>
                        <br>
                        <img class="img-fluid" id="image_preview" src="{{ getImageUrl($category->meta_image) }}"
                            alt="Profile Image" accept="image/png, image/jpeg" width="400px" height="209px">
                    </div>
                </div>
                <div class="field item form-group">
                    <label class="col-form-label col-md-3 col-sm-3  label-align">Status</label>
                    <div class="col-md-6 col-sm-6">
                        <select name="status" class="form-control" required>
                            <option value="1" {{$category->status == 1 ? 'selected' : ''}}>Active</option>
                            <option value="2" {{$category->status == 2 ? 'selected' : ''}}>Inactive</option>
                            <option value="3" {{$category->status == 3 ? 'selected' : ''}}>Delete</option>
                        </select>
                    </div>
                </div>

                <div class="ln_solid">
                    <div class="form-group">
                        <div class="col-md-6 offset-md-3 mt-3">
                            <button type='submit' class="btn btn-warning">Update</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@push('scripts')
    <script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'meta_description' );
    </script>
@endpush
@endsection

resources/views/backend/category/index.blade.php
@extends('layouts.backend')
@section('title', 'Category Lists')
@section('css')
    <link href="{{ asset('backend/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('backend/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
@endsection
@section('content')

<div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Category Management</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="btn btn-sm btn-success text-dark" href="{{ route('categories.create') }}"><i class="fa fa-plus"></i> Add New</a></li>
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
        <div class="x_content">
            <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
                    @include('backend.includes.message')
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th width="25%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($categories as $key => $category)
                            <tr>
                                <td>{{ ++$key }}</td>
                                <td>{{ $category->name }}</td>
                                <td>
                                    <a href="{{ route('categories.status', $category->id ) }}" class="btn btn-{{ $category->status == 1 ? 'success' : ($category->status == 3 ? 'danger disabled' : 'warning') }} btn-sm">{{\App\Enums\Status::from($category->status)->title()}}</a>
                                </td>
                                <td>
                                    <a class="btn btn-info btn-sm" href="{{ route('categories.show', $category->id) }}"><i class="fa fa-eye"></i></a>
                                    <a class="btn btn-primary btn-sm" href="{{ route('categories.edit', $category->id) }}"><i class="fa fa-edit"></i></a>
                                    <a href="{{ route('categories.destroy', $category->id ) }}" class="btn btn-danger btn-sm {{$category->status == 3 ? 'disabled' : ''}}"  onclick="showDeleteConfirmation()"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <!-- Datatables -->
    <script src="{{ asset('backend/vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('backend/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('backend/vendors/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('backend/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>

@endpush
@endsection

resources/views/backend/category/show.blade.php
@extends('layouts.backend')

@section('title', 'Show Category')
@section('content')

<div class="col-md-12 col-sm-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Show Category <small><a class="btn btn-warning" href="{{ route('categories.index') }}"> Back</a></small></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <span class="section">Category</span>
            <div class="field item form-group">
                <label class="col-form-label col-md-3 col-sm-3  label-align">Name<span class="required text-danger">*</span></label>
                <div class="col-md-6 col-sm-6">
                    <input class="form-control" disabled value="{{ $category->name }}"/>
                </div>
            </div>
            <div class="field item form-group">
                <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Title</label>
                <div class="col-md-6 col-sm-6">
                    <input class="form-control" disabled value="{{ $category->meta_title }}"/>
                </div>
            </div>
            <div class="field item form-group my-3">
                <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Description</label>
                <div class="col-md-6 col-sm-6">
                    {!! $category->meta_description !!}
                </div>
            </div>
            <div class="field item form-group">
                <label class="col-form-label col-md-3 col-sm-3  label-align">Meta Image</label>
                <div class="col-md-6 col-sm-6">
                    <img class="img-fluid" id="image_preview" src="{{ getImageUrl($category->meta_image) }}"
                        alt="Profile Image" accept="image/png, image/jpeg" width="1200px" height="627px">
                </div>
            </div>
            <div class="ln_solid">
                <div class="form-group">
                    <div class="col-md-6 offset-md-3 mt-3">
                        <a class="btn btn-primary btn-sm" href="{{ route('categories.edit', $category->id) }}"><i class="fa fa-edit"></i></a>
                        <a href="{{ route('categories.destroy', $category->id ) }}" class="btn btn-danger btn-sm {{$category->status == 3 ? 'disabled' : ''}}"  onclick="showDeleteConfirmation()"><i class="fa fa-trash"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection